sudo: false

language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3

services:
  - redis-server

before_script:
  - if [[ $TRAVIS_PHP_VERSION == "5.6" ]]; then composer require satooshi/php-coveralls --prefer-source; fi

script:
  - if [[ $TRAVIS_PHP_VERSION == "5.6" ]]; then make test-coverage; else make test; fi

after_success:
  - if [[ $TRAVIS_PHP_VERSION == "5.6" ]]; then php vendor/bin/php-coveralls -v; fi
