sudo: true

cache:
  directories:
    - $COMPOSER_CACHE_DIR
    - $HOME/.composer/cache
    - $TRAVIS_BUILD_DIR/build
    - $TRAVIS_BUILD_DIR/cache

language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4

env:
  global:
    - ICANBOOGIE_CLDR_REDIS_HOST=127.0.0.1
    - ICANBOOGIE_CLDR_REDIS_PORT=6379

services:
  - redis-server

before_script:
  - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

script:
  - if [[ $TRAVIS_PHP_VERSION == "7.1" ]]; then make test-coverage; else make test; fi

after_success:
  - if [[ $TRAVIS_PHP_VERSION == "7.1" ]]; then composer require php-coveralls/php-coveralls; fi
  - if [[ $TRAVIS_PHP_VERSION == "7.1" ]]; then php vendor/bin/php-coveralls -v; fi
