sudo: true

cache:
  directories:
    - $COMPOSER_CACHE_DIR
    - $HOME/.composer/cache
    - $TRAVIS_BUILD_DIR/build
    - $TRAVIS_BUILD_DIR/cache

language: php

php:
  - 5.6
  - 7.0
  - 7.3

env:
  global:
    - ICANBOOGIE_CLDR_REDIS_HOST=127.0.0.1
    - ICANBOOGIE_CLDR_REDIS_PORT=6379

services:
  - redis-server

before_script:
  - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

script:
  - if [[ $TRAVIS_PHP_VERSION == "5.6" ]]; then make test-coverage; else make test; fi

after_success:
  - if [[ $TRAVIS_PHP_VERSION == "5.6" ]]; then composer require satooshi/php-coveralls --prefer-source; fi
  - if [[ $TRAVIS_PHP_VERSION == "5.6" ]]; then php vendor/bin/php-coveralls -v; fi
