---
version: "3.2"
services:
  app:
    build: .
    environment:
      PHP_IDE_CONFIG: 'serverName=icanboogie-cldr'
      ICANBOOGIE_CLDR_REDIS_HOST: redis
      ICANBOOGIE_CLDR_REDIS_PORT: 6379
    depends_on:
    - redis
    volumes:
    - .:/app:delegated
    - ~/.composer:/root/.composer:delegated
    working_dir: /app

  redis:
    image: redis:4.0.6-alpine
