---
version: "3.0"
services:
  app:
    build: .
    environment:
      ICANBOOGIE_CLDR_REDIS_HOST: redis
      ICANBOOGIE_CLDR_REDIS_PORT: 6379
    depends_on:
    - redis
    volumes:
    - .:/app:delegated
    working_dir: /app

  redis:
    image: redis:5-alpine
